root = "."

tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["tmp", "vendor", "cmd/api/docs"]
  delay = 200

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[run]
  cmd = "./tmp/api"
